# This is a basic workflow to help you get started with Actions.
name: Node.js CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Triggers the workflow on pull request events also for the "main" branch
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-test"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Define the Node.js version to use
    strategy:
      matrix:
        node-version: [18.x] # Using v18 as specified in the README

    steps:
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Sets up the specified version of Node.js and enables npm caching
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Caches npm packages to speed up installation

      # --- SERVER ---
      # 3. Install dependencies for the server
      - name: Install server dependencies
        run: npm ci # 'ci' is recommended for CI for faster, more reliable builds
        working-directory: ./server

      # 4. Run the build script for the server (if it exists)
      - name: Run server build
        run: npm run build --if-present # '--if-present' won't fail if the script is missing
        working-directory: ./server

      # 5. Run the linter for the server (if it exists)
      - name: Run server lint
        run: npm run lint --if-present
        working-directory: ./server

      # 6. Run tests for the server
      - name: Run server tests
        run: npm test
        working-directory: ./server

      # --- CLIENT ---
      # 7. Install dependencies for the client
      - name: Install client dependencies
        run: npm ci
        working-directory: ./client

      # 8. Run the build script for the client (if it exists)
      - name: Run client build
        run: npm run build --if-present
        working-directory: ./client

      # 9. Run the linter for the client (if it exists)
      - name: Run client lint
        run: npm run lint --if-present
        working-directory: ./client

      # 10. Run tests for the client
      - name: Run client tests
        run: npm test
        working-directory: ./client
